apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: hello-world
  #  labels:
  #last_updated: 1
spec:
  rules:
  - host: flubber.dynalias.com
    http:
      paths:
      - path: /*
        backend:
          serviceName: hello-world
          servicePort: 80

