kind: Service
apiVersion: v1
metadata:
  name: configmap-secrets-docker-environment
spec:
  selector:
    app: configmap-secrets-docker-environment
  ports:
  - protocol: TCP
    #nodePort: 32132
    port: 80
    targetPort: 8080
